data_dir: datas

functions:
  download_train:
    _target_: functions.DownloadData # for training
    root: ${data_dir}
    train: true
    download: true
  download_valid:
    _target_: functions.DownloadData # for validation
    root: ${data_dir}
    train: false
    download: true